### ISSUE TITLE
Can't be used with npm

### ISSUE THREAD

**Issue by gf3** [romeovs/react-a11y#1]
When trying to install your package the [required main entry](https://github.com/romeovs/react-a11y/blob/master/package.json#L5) can't be found and the [src dir is ignored](https://github.com/romeovs/react-a11y/blob/master/.npmignore#L3). Here's what the installed package looks like:

```
node_modules/react-a11y/
├── docs/
├── test/
├── .babelrc
├── .eslintrc
├── .jshintignore
├── .jshintrc
├── .npmignore
├── .travis.yml
├── CHANGELOG.md
├── LICENSE
├── README.md
├── mkdocs.js
└── package.json
```

**Comment by romeovs** [comment]
Can you post the output of `npm install romeovs/reac-a11y`? I always forget how to do git hosted npm packages right without breaking the npm hosted package that it represents.

I'll look in to it soon! In the meantime, pull requests are welcome!

**Comment by gf3** [comment]
the install works fine, but since it's not being built and published the `lib` dir is not included (.gitignore) and the `src` dir is not included by npm (.npmignore)

**Comment by romeovs** [comment]
Can you try again please?

I just got a new internship at a cool company so most of my time is going there, but I want to keep this project alive!!

**Comment by erin-doyle** [comment]
This is still a problem.  The /lib directory is not being included in the package and so it throws an error when the library is included or required:

`Module not found: Error: Can't resolve 'react-a11y-alt/lib/index.js' `

**Comment by erin-doyle** [comment]
I think this issue will be fixed if we can just get a new version published @romeovs ?

**Comment by romeovs** [comment]
Done! Also, I'd be more than willing to transfer the nom package to someone that is more involved with the project.

**Comment by erin-doyle** [comment]
This is working for me now, thanks!  I think this issue can be closed.

**Comment by erin-doyle** [comment]
And I sent you an email on transferring the npm package @romeovs. 👍
