### ISSUE TITLE
Separate NPM package

### ISSUE THREAD

**Issue by todd-richmond** [romeovs/react-a11y#6]
There is significant good work in this fork that doesn't seem will get merged any time soon. Is it possible to build an official NPM package that can used w/o having to compile from git? That would give us a more stable release and simplify development and production builds

**Comment by tombigel** [comment]
+1

**Comment by romeovs** [comment]
I've published `react-a11y-alt` to npm! I do not have the time to do proper testing now, but maybe you guys can have a look?
