### ISSUE TITLE
Package should not have a postinstall that requires dev dependencies

### ISSUE THREAD

**Issue by nathanmarks** [romeovs/react-a11y#7]
Having issues installing the package from `npm` -- there shouldn't be a babel build step when installing the package from npm

**Comment by jkomusin** [comment]
There is a `prepublish` step that performs the babel build action, making the `postinstall` redundant. This should be as simple as removing the `postinstall` step entirely, right?

**Comment by romeovs** [comment]
@jkomusin did removed it!

**Comment by eldh** [comment]
You mind publishing a new version to npm?

**Comment by erin-doyle** [comment]
There's definitely still something wrong with the publishing of this.  I can install ok if I install `react-a11y-alt` but when requiring or importing the library I get errors:

`Module not found: Error: Can't resolve 'react-a11y-alt/lib/index.js' `

When I look at the install package in node_modules there is no lib directory.  So it seems as if build is not happening before publish maybe?

**Comment by erin-doyle** [comment]
This seems to be resolved?  I can install successfully but there are other issues (see #1 ).
